//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int ZipId { get; set; }
        public int UserId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual Zip Zip { get; set; }
    }
}
