//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add address that already exist or is null !.
        /// </summary>
        public static string AddressExceptionAdd {
            get {
                return ResourceManager.GetString("AddressExceptionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete address that doesn&apos;t exist !.
        /// </summary>
        public static string AddressExceptionDelete {
            get {
                return ResourceManager.GetString("AddressExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get address that doesn&apos;t exist !.
        /// </summary>
        public static string AddressExceptionGetById {
            get {
                return ResourceManager.GetString("AddressExceptionGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update address that doesn&apos;t exist !.
        /// </summary>
        public static string AddressExceptionUpdateById {
            get {
                return ResourceManager.GetString("AddressExceptionUpdateById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add city that already  exist or is null !.
        /// </summary>
        public static string CityExceptionAdd {
            get {
                return ResourceManager.GetString("CityExceptionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete city that doesn&apos;t exist !.
        /// </summary>
        public static string CityExceptionDelete {
            get {
                return ResourceManager.GetString("CityExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get city that doesn&apos;t exist !.
        /// </summary>
        public static string CityExceptionGetById {
            get {
                return ResourceManager.GetString("CityExceptionGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update city that doesn&apos;t exist !.
        /// </summary>
        public static string CityExceptionUpdateById {
            get {
                return ResourceManager.GetString("CityExceptionUpdateById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add county that already  exist or is null !.
        /// </summary>
        public static string CountyExceptionAdd {
            get {
                return ResourceManager.GetString("CountyExceptionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete county that doesn&apos;t exist !.
        /// </summary>
        public static string CountyExceptionDelete {
            get {
                return ResourceManager.GetString("CountyExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get county that doesn&apos;t exist !.
        /// </summary>
        public static string CountyExceptionGetById {
            get {
                return ResourceManager.GetString("CountyExceptionGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update county that doesn&apos;t exist !.
        /// </summary>
        public static string CountyExceptionUpdateById {
            get {
                return ResourceManager.GetString("CountyExceptionUpdateById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add email that already  exist or is null !.
        /// </summary>
        public static string EmailExceptionAdd {
            get {
                return ResourceManager.GetString("EmailExceptionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete email that doesn&apos;t exist !.
        /// </summary>
        public static string EmailExceptionDelete {
            get {
                return ResourceManager.GetString("EmailExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get email that doesn&apos;t exist !.
        /// </summary>
        public static string EmailExceptionGetById {
            get {
                return ResourceManager.GetString("EmailExceptionGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update email that doesn&apos;t exist !.
        /// </summary>
        public static string EmailExceptionUpdateById {
            get {
                return ResourceManager.GetString("EmailExceptionUpdateById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add state that already  exist or is null !.
        /// </summary>
        public static string StateExceptionAdd {
            get {
                return ResourceManager.GetString("StateExceptionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete state that doesn&apos;t exist !.
        /// </summary>
        public static string StateExceptionDelete {
            get {
                return ResourceManager.GetString("StateExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get state that doesn&apos;t exist !.
        /// </summary>
        public static string StateExceptionGetById {
            get {
                return ResourceManager.GetString("StateExceptionGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update state that doesn&apos;t exist !.
        /// </summary>
        public static string StateExceptionUpdateById {
            get {
                return ResourceManager.GetString("StateExceptionUpdateById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add user that already  exist or is null !.
        /// </summary>
        public static string UserExceptionAdd {
            get {
                return ResourceManager.GetString("UserExceptionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete user that doesn&apos;t exist !.
        /// </summary>
        public static string UserExceptionDelete {
            get {
                return ResourceManager.GetString("UserExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get user that doesn&apos;t exist !.
        /// </summary>
        public static string UserExceptionGetById {
            get {
                return ResourceManager.GetString("UserExceptionGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update user that doesn&apos;t exist !.
        /// </summary>
        public static string UserExceptionUpdateById {
            get {
                return ResourceManager.GetString("UserExceptionUpdateById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add zip that already  exist or is null !.
        /// </summary>
        public static string ZipExceptionAdd {
            get {
                return ResourceManager.GetString("ZipExceptionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete zip that doesn&apos;t exist !.
        /// </summary>
        public static string ZipExceptionDelete {
            get {
                return ResourceManager.GetString("ZipExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get zip that doesn&apos;t exist !.
        /// </summary>
        public static string ZipExceptionGetById {
            get {
                return ResourceManager.GetString("ZipExceptionGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update zip that doesn&apos;t exist !.
        /// </summary>
        public static string ZipExceptionUpdateById {
            get {
                return ResourceManager.GetString("ZipExceptionUpdateById", resourceCulture);
            }
        }
    }
}
